name: CICD Pipeline

on:
  push:
    branches:
      - main
  pullrequest:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
        # name: copy code from github repo to ubuntu VM machine
      - name: Checkout Repository to Ubuntu Runner
        uses: actions/checkout@v3

      - name: Install/Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      -name: Installing Dependencies
       run: npx prettier --write .

      -name: Run Prettier
       run: npm ci