name: CICD Pipeline

on:
  push:
    branches:
      - main
  pullrequest:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
        # name: copy code from github repo to ubuntu VM machine
      - name: Step1-Checkout Repository to Ubuntu Runner
        uses: actions/checkout@v3

      - name: Step2-Install/Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      -name: Step3-Installing Dependencies
       run: npm ci

      -name: Step4-Run Prettier
       run: npx prettier --check "**/*.{html,css,js}"

      -name: Step4-Run htmlhint
       run: npx htmlhint "**/*.html"       